home/urls.py
from django.urls import path
from .views import HomeView, send_contact, TestListView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('all/', TestListView.as_view(), name='test_vies'),
    path('send/', send_contact, name='send_contact'),
]

orders/urls.py
from django.urls import path
from .views import OrderView
from django.views.generic.base import TemplateView

app_name = 'orders'
urlpatterns = [
    path('demo/', TemplateView.as_view(template_name='orders/demo.html'), name='demo'),
    path('give/<slug:slug>/', OrderView.as_view(), name='test'),
]

home/models.py
from django.db import models
from django.utils import timezone
from django.utils.functional import cached_property
from easy_thumbnails.fields import ThumbnailerImageField


class Review(models.Model):
    name = models.CharField(verbose_name='ФИО', max_length=50, default=None, blank=True)
    text = models.TextField(verbose_name='Отзыв', default=None, blank=True)
    img = ThumbnailerImageField(verbose_name='автар', upload_to='review/', blank=True)
    date_review = models.DateField(verbose_name='дата отзыва', default=timezone.now, blank=True)
    fs = models.CharField(verbose_name='фейсбук', max_length=130, blank=True)
    inst = models.CharField(verbose_name='инстаграмм', max_length=130, blank=True)
    vk = models.CharField(verbose_name='вк', max_length=130, blank=True)

    class Meta:
        verbose_name_plural = 'отзывы'
        verbose_name = 'отзыв'
        ordering = ['date_review']

    def __str__(self):
        return '{}'.format(self.name)


class Test(models.Model):
    name = models.CharField(verbose_name='название теста', max_length=60, blank=True)
    slug = models.SlugField(verbose_name='название для ссылки', blank=True)
    description = models.TextField(verbose_name='описание')

    class Meta:
        verbose_name_plural = 'тесты'
        verbose_name = 'тест'
        ordering = ['name']

    def __str__(self):
        return '{}'.format(self.name)

    @cached_property
    def questions(self):
        return self.question_set.all()


class Question(models.Model):
    name = models.CharField(verbose_name='Вопрос', max_length=300, blank=True)
    test = models.ForeignKey(Test, verbose_name='тест', on_delete=models.CASCADE, blank=True)
    rights = models.SmallIntegerField(verbose_name='порядок', default=None, blank=True, db_index=True)

    class Meta:
        verbose_name_plural = 'Вопросы'
        verbose_name = 'Вопрос'
        ordering = ['rights']

    def __str__(self):
        return '{}'.format(self.name)

    @cached_property
    def answers(self):
        return self.answer_set.all()


class Answer(models.Model):
    name = models.CharField(verbose_name='ответ', max_length=300, blank=True)
    question = models.ForeignKey(Question, verbose_name='вопрос', on_delete=models.CASCADE, blank=True)
    rights = models.SmallIntegerField(verbose_name='балы', default=None, blank=True, db_index=True)

    class Meta:
        verbose_name_plural = 'ответы'
        verbose_name = 'ответ'
        ordering = ['name']

    def __str__(self):
        return '{}'.format(self.name)


class PostStudy(models.Model):
    name = models.CharField(verbose_name='название', max_length=300, blank=True)
    img = ThumbnailerImageField(verbose_name='картинка', upload_to='study/', blank=True)
    description = models.TextField(verbose_name='описание', default='', blank=True)

    class Meta:
        verbose_name_plural = 'Преимущества обучения'
        verbose_name = 'Преимущества обучения'
        ordering = ['name']

    def __str__(self):
        return '{}'.format(self.name)


class CourseHome(models.Model):
    name = models.CharField(verbose_name='название курса', default=None, max_length=50, blank=True)
    description = models.CharField(verbose_name='описание', default=None, max_length=50, blank=True)
    price = models.CharField(verbose_name='цена за курс', help_text='с пробелом', max_length=20, default=None, blank=True)
    all_time = models.CharField(verbose_name='Общее время курса', default=None, max_length=50, blank=True)
    icons = models.CharField(verbose_name='иконка', default=None, max_length=20, blank=True)

    class Meta:
        verbose_name_plural = 'Прайс курсов'
        verbose_name = 'Курс'
        ordering = ['name']

    def __str__(self):
        return '{}'.format(self.name)

    @cached_property
    def conditions(self):
        return self.conditionscoursehome_set.all()


class ConditionsCourseHome(models.Model):
    conditions = models.CharField(verbose_name='Условие', default=None, max_length=50, blank=True)
    course = models.ForeignKey(CourseHome, verbose_name='курс', on_delete=models.CASCADE, blank=True)

    class Meta:
        verbose_name_plural = 'Прайс курсов'
        verbose_name = 'Курс'
        ordering = ['id']

    def __str__(self):
        return '{}'.format(self.conditions)

home/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(max_length=100)
    tel = forms.CharField(max_length=16)
    email = forms.EmailField()

home/views.py
from django.views.generic.base import TemplateView
from .models import Review, PostStudy, Test, CourseHome
from .forms import ContactForm
from django.core.mail import send_mail
from oxbridge import settings
from django.views.generic.list import ListView
from django.views.decorators.http import require_http_methods
from django.http import JsonResponse
# Create your views here.


class TestListView(ListView):
    template_name = 'home/test_list.html'
    model = Test
    context_object_name = 'tests'


class HomeView(TemplateView):
    template_name = 'home/home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['reviews'] = Review.objects.all()
        context['posts'] = PostStudy.objects.all()
        context['prices'] = CourseHome.objects.all()
        return context

    def post(self, request, *args, **kwargs):
        print(request.POST)
        form = ContactForm(request.POST)
        data = {}
        if form.is_valid():
            email_subject = 'OXBRIDGE.KZ :: Сообщение через контактную форму '
            email_body = "С сайта отправлено новое сообщение\n\n" \
                         "Имя отправителя: %s \n" \
                         "E-mail отправителя: %s \n\n" \
                         "Сообщение: \n" \
                         "%s " % \
                         (form.cleaned_data['name'], form.cleaned_data['email'], form.cleaned_data['tel'])
            if True:
                send_mail(email_subject, email_body, settings.EMAIL_HOST_USER, ['info@oxbridge.kz'],
                          fail_silently=False)
                data['ok'] = 'Ваша заявка успешно отправллено!'
                return JsonResponse(data)
            else:
                data['no'] = 'Упс ошибка'
                return JsonResponse(data)
        else:
            data['no'] = 'Упс ошибка'
            return JsonResponse(data)


@require_http_methods(["POST"])
def send_contact(request):
    form = ContactForm(request.POST)
    data = {}
    if form.is_valid():
        email_subject = 'OXBRIDGE.KZ :: Сообщение через контактную форму '
        email_body = "С сайта отправлено новое сообщение\n\n" \
                     "Имя отправителя: %s \n" \
                     "E-mail отправителя: %s \n\n" \
                     "Сообщение: \n" \
                     "%s " % \
                     (form.cleaned_data['name'], form.cleaned_data['email'], form.cleaned_data['tel'])
        if True:
            send_mail(email_subject, email_body, settings.EMAIL_HOST_USER, ['info@oxbridge.kz'],
                      fail_silently=False)
            data['ok'] = 'Ваша заявка успешно отправллено!'
            return JsonResponse(data)
        else:
            data['no'] = 'Упс ошибка'
            return JsonResponse(data)
    else:
        return JsonResponse('no', content_type='text/html')

home/templates/home/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{% endblock %}
{% block description %}{% endblock %}
{% block author %}{% endblock %}
{% block content %} {% endblock %}

home/templates/home/test_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Тесты
{% endblock %}
{% block description %}

{% endblock %}
{% block author %}

{% endblock %}


{% block content %}
<!-- Hero Block
================================================== -->

<div class="section padding-top-1st padding-bottom-1st over-hide" style="padding-top: 540px;">
    <div class="parallax" style="background-image: url('{% static 'img/parallax-pages-6.jpg' %}')"></div>
    <div class="grey-fade-over"></div>
    <div class="container z-bigger">
        <div class="row">
            <div class="col-md-7 parallax-fade-top">
                <div class="main-title on-dark text-left mb-0">
                    <h2>Careers</h2>
                    <div class="main-subtitle-bottom mt-4">Some people think design means how it looks. But of course, if you dig deeper, it's really how it works.</div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
</div>

<!-- Block
================================================== -->

<div class="section background-white padding-top-bottom over-hide z-bigger-2">
    <div class="container">
        <div class="row">
            {% for test in tests %}
            <div class="col-lg-12 pb-3" data-scroll-reveal="enter bottom move 40px over 0.8s after 0.2s">
                <div class="services-box-1 border-on-light border-on-hover text-left over-hide">
                    <h5>{{ test.name }}</h5>
                    <p class="mt-3 mb-4">{{ test.description }}</p>
                    <a href="{% url 'orders:test' test.slug %}" class="btn-link btn-primary">Пройти</a>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}