home/urls.py
from django.urls import path
from .views import HomeView, send_contact, TestListView

app_name = 'home'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('all/', TestListView.as_view(), name='test_vies'),
    path('send/', send_contact, name='send_contact'),
]

templates/includes/footer.html
{% load static %}

<!-- Footer Light Block
================================================== -->

<div class="section pt-4 background-dark-2 over-hide footer-1 dark z-bigger-2 pb-5">
    <div class="container ">
        <div class="row">
            <div class="col-md-8 pr-md-3 maps col-12" id="maps" style="background-image: url({% static 'img/maps.jpeg' %})">
            </div>
            <div class="col-md-3 col-12 mt-4 mt-md-0 logo-footer-100">
                <h4 class="text-white">Контакты</h4>
                <div class="separator-wrap">
                    <span class="separator"><span class="separator-line dashed"></span></span>
                </div>
                <ul class="list-style mt-3 mb-3">
                    <li><i class="fa fa-envelope-o"></i><a href="mailto:info@oxbridge.kz">info@oxbridge.kz</a></li>
                    <li><i class="fa fa-phone"></i><a href="tel:87475192787">+7(747)519-27-87</a></li>
                    <li><i class="fa fa-skype"></i><a href="skype:oxbridgestudy2017@gmail.com">oxbridgestudy2017@gmail.com</a></li>
                </ul>
                <ul class="footer-social" style="float: none">
                    <li class="twitter">
                        <a href="#">Tw</a>
                    </li>
                    <li class="facebook">
                        <a href="https://www.facebook.com/oxbridgestudy.astana">Fb</a>
                    </li>
                    <li class="google">
                        <a href="https://www.instagram.com/oxbridge_study_astana">Inst</a>
                    </li>
                    <li class="vimeo">
                        <a href="https://vk.com/oxbridgestudyastana">Vk</a>
                    </li>
                    <li class="twitter">
                        <a href="skype:oxbridgestudy2017@gmail.com">Skype</a>
                    </li>
                </ul>
                <div class="separator-wrap">
                    <span class="separator"><span class="separator-line dashed"></span></span>
                </div>
            </div>
        </div>
    </div>
</div>

templates/includes/header.html
{% load static %}
<!-- Nav and Logo
	================================================== -->

<div id="menu-wrap" class="cbp-af-header white-menu-background-no-trans menu-fixed-padding-small-same menu-shadow">
    <div class="container-fluid max-width-90">
        <div class="row">
            <div class="col-md-12">
                <nav class="navbar navbar-toggleable-md navbar-light bg-inverse bg-faded">
                    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavMenuMain" aria-controls="navbarNavMenuMain" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'home:index' %}">
                        <img src="{% static 'img/logo.png' %}">
                    </a>
                    <div class="collapse navbar-collapse justify-content-end" id="navbarNavMenuMain">
                        <ul class="navbar-nav">
                            <li class="nav-item dropdown mega-menu">
                                <a class="nav-link" href="{% url 'home:index' %}" >
                                    Главное
                                </a>
                            </li>
                            <li class="nav-item dropdown mega-menu">
                                <a class="nav-link" href="{% url 'home:test_vies' %}" >
                                    Пройти тесты
                                </a>
                            </li>
                            <li class="nav-item dropdown mega-menu">
                                <a class="nav-link" href="http://go.2gis.com/2e34s" >
                                    Адрес
                                </a>
                            </li>
                            <li class="nav-item dropdown mega-menu">
                                <a class="nav-link" href="tel:87475192787" >
                                    Тел:+7(747)519-27-87
                                </a>
                            </li>
                            <li class="nav-item icons-item-menu">
                                <a class="nav-link link-me ml-4" href="https://www.facebook.com/oxbridgestudy.astana"><i class="funky-ui-icon icon-Facebook-2 f-size-icon f-size-icon1"></i></a>
                            </li>
                            <li class="nav-item icons-item-menu">
                                <a class="nav-link link-me ml-4" href="https://www.instagram.com/oxbridge_study_astana"><i class="funky-ui-icon icon-Instagram f-size-icon f-size-icon1"></i></a>
                            </li>
                            <li class="nav-item icons-item-menu">
                                <a class="nav-link link-me ml-4" href="https://vk.com/oxbridgestudyastana"><i class="funky-ui-icon icon-Vimeo f-size-icon f-size-icon1"></i></a>
                            </li>
                            <li class="nav-item icons-item-menu">
                                <a class="nav-link link-me ml-4" href="skype:oxbridgestudy2017@gmail.com"><i class="funky-ui-icon icon-Skype f-size-icon f-size-icon1"></i></a>
                            </li>
                            <li class="nav-item icons-item-menu">
                                <a class="nav-link link-me ml-4" href="https://api.whatsapp.com/send?phone=77475192787"><i class="fa fa-whatsapp f-size-icon f-size-icon1"></i></a>
                            </li>

                        </ul>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</div>